Neos:
  Neos:
    Ui:
      resources:
        javascript:
          'Flowpack.RestrictCreation:RestrictCreation':
            resource: resource://Flowpack.RestrictCreation/Public/JavaScript/RestrictCreation/Plugin.js
    userInterface:
      translation:
        autoInclude:
          'Flowpack.RestrictCreation':
            - Main